### ISSUE TITLE
Pending database changes

### ISSUE THREAD

**Issue by vivrelavie** [vivrelavie/FLIGHT-RESERVATION#12]
# Pending changes in database

| # | Table Name | Issue Description | Status |
|--------|--------|--------|--------|
| 1 | Airport | No airport table | Fixed | 
| 2 | Airport | No airport location | Fixed |
| 3 | Accounts | Remove accounts data (Drop foreign key then re-add) | Fixed |
| 4 | All tables | Primary Keys are not AUTO_INCREMENT | Fixed |
| 5 | Accounts | Remove Phone number column | Fixed |

**Comment by Luhartt** [comment]
wow
