### ISSUE TITLE
[BUG] Flight Booking

### ISSUE THREAD

**Issue by vivrelavie** [vivrelavie/FLIGHT-RESERVATION#34]
## Describe the bug

Flight booking continues without a selected flight.

### Files

Available Flights

### To Reproduce
1. Go to flight booking
2. Search flight
3. Select flight (for example AP789)
4. Unselect flight and press continue
5. Form continues and accepts AP789

### Expected behavior

Validation should prevent form from continuing if the flight is unselected.

### Screenshots

Unselected flight
![image](https://github.com/user-attachments/assets/86184c37-149b-4bc2-9fda-fa5e4540ee3a)

Flight is submitted and continues to guest details
![image](https://github.com/user-attachments/assets/354b7d60-2e18-428b-9fa2-2f4f176fd761)

## Tasks

- [x] Additional validation or make string null when flight is unselected

**Comment by Luhartt** [comment]
Fixed

Also added validation if there is no selected airplane

selected and deselected and clicked continue
![image](https://github.com/user-attachments/assets/437fc2a8-ceab-4a3a-94fe-5254a825494b)
