### ISSUE TITLE
[BUG] Flight Booking - Payment validation

### ISSUE THREAD

**Issue by vivrelavie** [vivrelavie/FLIGHT-RESERVATION#35]
## Describe the bug

Card payment validation displays "Fill up all fields" kahit may laman lahat ng textbox

### Files

Payment Details

### To Reproduce
1. Select card
2. Select Gcash
3. Go back to card
4. Enter all details
5. Continue
6. Encounter bug

### Expected behavior

Should continue after entering in all fields

### Screenshots

![image](https://github.com/user-attachments/assets/fe26656b-7e21-465a-8073-da61f7e4c56e)
![image](https://github.com/user-attachments/assets/fb607fb0-2a09-4fd4-9901-43465e7a4574)
![image](https://github.com/user-attachments/assets/e8dfb201-b26a-44d1-8db7-ad1cdd1a0580)

### Additional context
Gcash works but does not go to flight booking success

## Tasks

- [x] fix this

**Comment by Luhartt** [comment]
Fixed
